import { useMemo, useRef, useState } from 'react';
import { Aperture, Upload, Image as ImageIcon, SlidersHorizontal, ScanFace, WandSparkles, Download, RotateCcw, X, ChevronLeft, ChevronRight } from 'lucide-react';

type Photo = { id: string; name: string; url: string; file: File };
type Adjustments = { exposure: number; contrast: number; saturation: number; warmth: number };
const initial: Adjustments = { exposure: 0, contrast: 0, saturation: 0, warmth: 0 };

export default function App() {
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [active, setActive] = useState(0);
  const [adjust, setAdjust] = useState<Adjustments>(initial);
  const inputRef = useRef<HTMLInputElement>(null);
  const current = photos[active];
  const filter = useMemo(() => current ? `brightness(${Math.pow(2, adjust.exposure / 100)}) contrast(${100 + adjust.contrast}%) saturate(${100 + adjust.saturation}%) sepia(${Math.max(0, adjust.warmth) / 250}) hue-rotate(${Math.min(0, adjust.warmth) / 2}deg)` : 'none', [current, adjust]);
  function addFiles(files: FileList | null) {
    if (!files) return;
    const accepted = Array.from(files).filter(f => ['image/jpeg','image/png','image/webp'].includes(f.type));
    const next = accepted.map(file => ({ id: crypto.randomUUID(), name: file.name, url: URL.createObjectURL(file), file }));
    setPhotos(prev => [...prev, ...next]);
    if (!current && next.length) setActive(0);
  }
  function remove(id: string) {
    setPhotos(prev => { const index = prev.findIndex(p => p.id === id); const item = prev[index]; if (item) URL.revokeObjectURL(item.url); const next = prev.filter(p => p.id !== id); setActive(Math.max(0, Math.min(index <= active ? active - 1 : active, next.length - 1))); return next; });
  }
  function setValue(key: keyof Adjustments, value: number) { setAdjust(prev => ({ ...prev, [key]: value })); }
  return <main className="app">
    <header className="topbar"><div className="brand"><span className="brand-icon"><Aperture size={20}/></span><span>PHOTO<span className="muted"> / AI EDITOR</span></span><span className="version">BROWSER PROTOTYPE</span></div><div className="top-actions"><span className="status"><i/> LOCAL WORKSPACE</span><button className="export" disabled={!photos.length} onClick={() => alert('Экспорт появится на следующем этапе. Сейчас настройки применяются только в предпросмотре.')}><Download size={15}/> Export batch</button></div></header>
    <section className="workspace">
      <aside className="library"><div className="section-head"><span>PROJECT LIBRARY</span><span className="count">{photos.length.toString().padStart(2,'0')}</span></div><div className="project-name"><div className="folder">▦</div><div><strong>Untitled project</strong><small>Session · Unsaved</small></div></div><div className="library-label">IMAGES <span>{photos.length}</span></div>
      {photos.length === 0 ? <button className="dropzone" onClick={() => inputRef.current?.click()}><Upload size={22}/><b>Import photos</b><small>JPEG, PNG, WebP</small></button> : <div className="thumb-list">{photos.map((p,i)=><button key={p.id} className={`thumb ${i===active?'selected':''}`} onClick={()=>{setActive(i);setAdjust(initial);}}><img src={p.url}/><span className="thumb-index">{String(i+1).padStart(2,'0')}</span><span className="thumb-name">{p.name}</span><span className="remove" onClick={e=>{e.stopPropagation();remove(p.id);}}><X size={13}/></span></button>)}</div>}
      <button className="add-more" onClick={()=>inputRef.current?.click()}><Upload size={14}/> Add images</button><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={e=>addFiles(e.target.files)}/><div className="library-foot"><span>SUPPORTED FORMATS</span><p>JPG · PNG · WEBP</p><p className="subtle">RAW support planned</p></div></aside>
      <section className="canvas-area"><div className="canvas-toolbar"><div className="crumb">PROJECT <span>/</span> {current ? current.name.toUpperCase() : 'NO IMAGE SELECTED'}</div><div className="view-controls"><span className="view-tag">FIT</span><span className="view-tag">100%</span></div></div><div className="canvas">{current ? <><div className="image-wrap"><img className="main-image" src={current.url} style={{filter}}/><div className="image-badge">PREVIEW · ADJUSTMENTS</div></div><div className="image-nav"><button disabled={active===0} onClick={()=>{setActive(active-1);setAdjust(initial)}}><ChevronLeft size={16}/></button><span>{String(active+1).padStart(2,'0')} / {String(photos.length).padStart(2,'0')}</span><button disabled={active===photos.length-1} onClick={()=>{setActive(active+1);setAdjust(initial)}}><ChevronRight size={16}/></button></div></> : <div className="empty"><div className="empty-icon"><ImageIcon size={28}/></div><h2>Your workspace is ready</h2><p>Import a set of images to start reviewing and adjusting your photo series.</p><button className="primary" onClick={()=>inputRef.current?.click()}><Upload size={15}/> Import photos</button><small>Start with JPEG, PNG or WebP files</small></div>}</div><div className="filmstrip">{photos.map((p,i)=><button key={p.id} className={i===active?'film-active':''} onClick={()=>{setActive(i);setAdjust(initial)}}><img src={p.url}/></button>)}{photos.length>0&&<button className="film-add" onClick={()=>inputRef.current?.click()}><Upload size={15}/></button>}</div></section>
      <aside className="inspector"><div className="section-head"><span>IMAGE WORKFLOW</span><span className="live">● LIVE</span></div><div className="workflow"><div className="step active"><span className="step-num">01</span><div><b>Image review</b><small>Import & select frames</small></div><span className="step-state">ACTIVE</span></div><div className="step disabled"><span className="step-num">02</span><div><b>AI Analysis</b><small>Scene, light, skin, exposure</small></div><span className="soon">SOON</span></div><div className="step disabled"><span className="step-num">03</span><div><b>Neutralization</b><small>Technical base correction</small></div><span className="soon">SOON</span></div><div className="step disabled"><span className="step-num">04</span><div><b>Creative grade</b><small>Series-aware color profile</small></div><span className="soon">SOON</span></div><div className="step disabled"><span className="step-num">05</span><div><b>AI Retouch</b><small>Skin & detail refinement</small></div><span className="soon">SOON</span></div></div><div className="panel-title"><SlidersHorizontal size={15}/> MANUAL PREVIEW <button onClick={()=>setAdjust(initial)} title="Reset"><RotateCcw size={13}/></button></div>{([['exposure','Exposure',-100,100],['contrast','Contrast',-50,50],['saturation','Saturation',-50,50],['warmth','Warmth',-100,100]] as const).map(([key,label,min,max])=><div className="slider-row" key={key}><div className="slider-label"><span>{label}</span><span className="slider-value">{adjust[key]>0?'+':''}{adjust[key]}</span></div><input type="range" min={min} max={max} value={adjust[key]} disabled={!current} onChange={e=>setValue(key,Number(e.target.value))}/><div className="slider-scale"><span>{key==='exposure'?'−1 EV':key==='warmth'?'Cool':'−'}</span><span>{key==='exposure'?'+1 EV':key==='warmth'?'Warm':'+'}</span></div></div>)}<div className="notice"><WandSparkles size={15}/><span>Adjustments are non-destructive preview controls. AI processing and rendered export are not connected yet.</span></div><div className="inspector-bottom"><button className="ai-button" disabled><ScanFace size={15}/> Analyze series <span>COMING SOON</span></button><small>KIE.ai provider integration will be enabled after server credentials are configured.</small></div></aside>
    </section>
  </main>;
}
